### ISSUE TITLE
not working in free mode.

### ISSUE THREAD

**Issue by TwistingTwists** [anirudt/concert-master#1]
```
concert-master git:(master) ✗ python concert.py -n1 -f

Let us start now!
Projecting for next 10 seconds.
Traceback (most recent call last):
  File "concert.py", line 343, in <module>
    ret = webCamCapture()
  File "concert.py", line 248, in webCamCapture
    hsv, contours, hierarchy = skin_detect_ycbcr(frame)
  File "concert.py", line 148, in skin_detect_ycbcr
    contours, hierarchy = cv2.findContours(skinRegion, cv2.RETR_EXTERNAL, 
cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack
```

The above is the output from terminal.

**Comment by anirudt** [comment]
Hi,

I haven't run into this before.
1. Is this the first epoch, or did it play some music and cross over to the next epoch?
2. Since this is an OpenCV API which returns just these two values, you might have to provide some more information regarding this, and investigate the reproducibility of this issue in other cases. Please check the version of OpenCV, this was developed on 2.4.8.

**Comment by anirudt** [comment]
@TwistingTwists : Do check up, I've fixed the issue in the latest commit. 

Picked up a fresh 3.0.0-dev build, and turns out that it was a change in the API. Solved it using the fix outlined [here](http://answers.opencv.org/question/32248/open-cv-30-findcontours-return-too-many-value-to-unpack/).
